export const defaultSections = [
  {
    id: 'profile',
    visible: true,
    order: 1,
    title: { zh: '我是谁', en: 'Who I Am' },
  },
  {
    id: 'persona',
    visible: true,
    order: 2,
    title: { zh: '性格与兴趣', en: 'Personality & Interests' },
  },
  {
    id: 'projects',
    visible: true,
    order: 3,
    title: { zh: '个人项目', en: 'Personal Projects' },
  },
  {
    id: 'creative',
    visible: true,
    order: 4,
    title: { zh: '编曲与兴趣创作', en: 'Music & Creative Works' },
  },
  {
    id: 'timeline',
    visible: true,
    order: 5,
    title: { zh: '重要记录', en: 'Notable Records' },
  },
  {
    id: 'contact',
    visible: true,
    order: 6,
    title: { zh: '找到我', en: 'Find Me' },
  },
];

export const profileModes = [
  { id: 'persona', label: { zh: '人格档案式', en: 'Persona' } },
  { id: 'resume', label: { zh: '简历式', en: 'Resume' } },
];

export const defaultContentItems = [
  {
    id: 'profile-name',
    section: 'profile',
    type: 'text',
    mode: 'all',
    visible: true,
    order: 1,
    title: { zh: '称呼', en: 'Name' },
    description: {
      zh: '这里可以放真实姓名、昵称，或根据场景切换不同称呼。',
      en: 'This can show a real name, nickname, or a context-specific name.',
    },
  },
  {
    id: 'profile-persona-intro',
    section: 'profile',
    type: 'text',
    mode: 'persona',
    visible: true,
    order: 2,
    title: { zh: '人格档案', en: 'Personal Snapshot' },
    description: {
      zh: '一个喜欢把想法做成东西的人。这里之后可以写成更自然、更像自己的介绍。',
      en: 'Someone who enjoys turning ideas into tangible things. This can later become a more personal introduction.',
    },
  },
  {
    id: 'profile-resume-intro',
    section: 'profile',
    type: 'text',
    mode: 'resume',
    visible: true,
    order: 3,
    title: { zh: '简历摘要', en: 'Resume Summary' },
    description: {
      zh: '这里放面向招聘的简短摘要，包括技术方向、项目经验和核心能力。',
      en: 'A recruiting-oriented summary covering technical focus, project experience, and core strengths.',
    },
  },
  {
    id: 'persona-traits',
    section: 'persona',
    type: 'text',
    visible: true,
    order: 10,
    title: { zh: '性格', en: 'Personality' },
    description: {
      zh: '可以写你的做事方式、相处方式、价值观，保留一点真实的个人语气。',
      en: 'Describe how you work, relate to others, and what you value, while keeping a personal voice.',
    },
  },
  {
    id: 'persona-interests',
    section: 'persona',
    type: 'text',
    visible: true,
    order: 11,
    title: { zh: '兴趣爱好', en: 'Interests' },
    description: {
      zh: '足球、编曲、写代码、观察生活。这里可以继续细分成多个条目。',
      en: 'Football, arranging music, coding, and observing everyday life. These can be split into separate entries later.',
    },
  },
  {
    id: 'project-console-site',
    section: 'projects',
    type: 'project',
    visible: true,
    order: 20,
    year: '2026',
    title: { zh: '个人档案控制台', en: 'Personal Archive Console' },
    description: {
      zh: '一个静态个人网站模板，通过本地控制台切换板块、条目、语言和主题。',
      en: 'A static personal website template with a local console for sections, items, language, and theme.',
    },
    tags: ['React', 'Vite', 'Bootstrap', 'GitHub Pages'],
  },
  {
    id: 'project-placeholder',
    section: 'projects',
    type: 'project',
    visible: true,
    order: 21,
    year: 'TBD',
    title: { zh: '下一个个人项目', en: 'Next Personal Project' },
    description: {
      zh: '这里预留给之后真正要展示的项目，可以补链接、截图、技术栈和成果。',
      en: 'Reserved for a real project, with links, screenshots, stack, and outcomes to be added later.',
    },
    tags: ['Planning'],
  },
  {
    id: 'creative-music',
    section: 'creative',
    type: 'project',
    visible: true,
    order: 30,
    year: 'Ongoing',
    title: { zh: '编曲练习', en: 'Arrangement Practice' },
    description: {
      zh: '兴趣创作不必伪装成技术项目，它可以单独展示你的审美、耐心和表达方式。',
      en: 'Creative work does not need to pretend to be a technical project; it can show taste, patience, and expression.',
    },
    tags: ['Music', 'Arrangement', 'Creative'],
  },
  {
    id: 'timeline-bicycle-kick',
    section: 'timeline',
    type: 'timeline',
    visible: true,
    order: 40,
    date: 'TBD',
    title: { zh: '倒钩名场面', en: 'The Bicycle Kick Moment' },
    description: {
      zh: '某年某月某日，踢进一个值得写进个人时间线的倒钩。',
      en: 'A bicycle kick good enough to earn a place in the personal timeline.',
    },
  },
  {
    id: 'timeline-honor',
    section: 'timeline',
    type: 'timeline',
    visible: true,
    order: 41,
    date: 'TBD',
    title: { zh: '荣誉或重要事件', en: 'Honor or Milestone' },
    description: {
      zh: '这里可以记录荣誉、比赛、作品发布、人生节点或深刻经历。',
      en: 'A place for awards, competitions, launches, life milestones, or meaningful experiences.',
    },
  },
  {
    id: 'contact-github',
    section: 'contact',
    type: 'text',
    visible: true,
    order: 50,
    title: { zh: 'GitHub', en: 'GitHub' },
    description: {
      zh: '之后可以放 GitHub、邮箱、社交媒体，或保持隐藏。',
      en: 'GitHub, email, and social links can be added here later, or kept hidden.',
    },
  },
];
